# Use case Configuration for sof-hda-dsp

SectionVerb {
	EnableSequence [
		disdevall ""
	]

	Value.TQ "HiFi"
}

Include.analog-mic.File "/HDA/HiFi-mic.conf"
Include.dmic.File "dmic.conf"
Include.hdmi.File "/Intel/sof-hda-dsp/Hdmi.conf"
